//! BMI2-tier sequence-section decoder.
//!
//! Issue #279 round 3 Phase 3: the BMI2-tier `decode_and_execute_sequences_bmi2`
//! is generated by the `define_x86_seq_decoder_tier!` macro with the full
//! decoder body in BMI2 `#[target_feature]` scope. The hot
//! `decode_one_sequence_bmi2` uses `peek_bits_triple_bmi2` directly so
//! `_pext_u64` inlines as the 3-extract sequence instead of crossing
//! the `extract_triple_pext` CALL boundary.

crate::define_x86_seq_decoder_tier! {
    kernel = crate::cpu_kernel::Bmi2Kernel,
    target_feature = "bmi2",
    decode_fn = decode_and_execute_sequences_bmi2,
    loop_fn = run_pipelined_loop_bmi2,
    decode_one_fn = decode_one_sequence_bmi2,
}
